wildberries-tech/ui-react

- CHANGELOG.md
- src/components/textarea/__tests__/__snapshots__/index.tsx.snap
- src/components/textarea/__tests__/index.tsx
- src/components/textarea/index.module.pcss
- src/components/textarea/index.module.pcss.d.ts
- src/components/textarea/index.tsx
- src/components/textarea/stories/index.docs.mdx
- src/components/textarea/stories/index.stories.tsx
- src/index.ts
> Компонент Textarea

- packages/ui-react/src/hooks/use-classnames/stories/index.stories.mdx
change IStyles to TStyles, because IStyles is not exist
> fix storybook useClassnames import

- packages/ui-react/src/components/date-picker/index.tsx
> task(ADS-5384_2): fix datepicker

- packages/ui-react/src/components/date-picker/index.module.pcss
- packages/ui-react/src/components/date-picker/index.tsx
- packages/ui-react/src/hooks/use-format-with-options/__tests__/index.ts
- packages/ui-react/src/hooks/use-format-with-options/index.ts
- fix hook use-format-with-options
- fix date-picker styles
> Feature weekdays

- packages/ui-react/src/components/date-picker/index.tsx
> task(ADS-5384_4): fix datepicker

- packages/ui-react/src/components/modal/index.tsx
- packages/ui-react/src/components/popover/index.tsx
- fix modal component overwrite styles
- fix popover warning (react-laag)
> task(ADS-5435): fix modal

- packages/ui-react/src/components/pagination/index.module.pcss
- packages/ui-react/src/components/pagination/index.module.pcss.d.ts
- packages/ui-react/src/components/pagination/index.tsx
- add isOpen for arrow in pagination dropdown
> task(ADS-5477): fix pagination dropdown arrow

- packages/ui-react/src/components/input-code/index.module.pcss
- packages/ui-react/src/components/input-code/index.tsx
- packages/ui-react/src/components/select/__tests__/__snapshots__/index.tsx.snap
ограничение на ввод символов, исправление проблемы отображение теней на iPhone
> Доработка компонента input-code

- packages/ui-react/src/components/select/index.module.pcss
> fix-select-text-position:

- packages/ui-react/src/components/pagination/__tests__/__snapshots__/index.tsx.snap
- packages/ui-react/src/components/pagination/__tests__/index.tsx
- packages/ui-react/src/components/pagination/index.tsx
- add new props for pagination
- add test
- add snapshot
> add-props-for-pagination:

- packages/ui-react/src/components/input-date/index.module.pcss
- add white background for icon in calendar (input-date)
> task(ADS-5769): [FRONT] - скрыть стандартную иконку в календаре

- packages/ui-react/src/components/modal/v2/index.tsx
> task(ADS-5483): [FRONT] - fix modal v2 body scroll lock

- package-lock.json
- packages/ui-react/package.json
- packages/ui-react/src/components/modal/v1/index.tsx
- packages/ui-react/src/components/modal/v2/index.tsx
- packages/ui-react/src/hooks/use-body-scroll-lock/__tests__/index.tsx
- packages/ui-react/src/hooks/use-body-scroll-lock/index.ts
- packages/ui-react/src/index.ts
- create new hook useBodyScrollLock
- add hook to modal
> task(ADS-5483): [FRONT] - create new hook

- package-lock.json
- package.json
- packages/ui-react/src/components/switch/v2/index.tsx
https://youtrack.wildberries.ru/issue/AP-815/V-komponente-switch-peredelat-state-na-merge-state
Кейс который без этого не решить:
Мы кликаем на switch который в статусе checked, при этом в логике сверху его state остается checked: true т к допустим не выполнилось какое-то условие.
это можно было бы решить с помощью:
useEffect(() => {
props.checked && setState(props.checked)
})
в компоненте switch, чтоб на каждый чих оно сверялось с контролируемым стейтом, но тогда будет все равно быстрый но "прыжок" свича туда-сюда, что не красиво.
Чтоб этого избежать нужно написать огромный контроллер на проверку всего и сразу (посмотрел в готовых либах), в rc-utils он есть готовый, библиотека не имеет зависимостей кроме бабеля, так что самое простое - это взять ее, т к хук еще и в других компонентах с …
> task(AP-815): [FRONT] - changed switch state to merged state

- packages/ui-react/src/components/checkbox/v2/index.tsx
https://youtrack.wildberries.ru/issue/AP-852/V-ui-kit-v-komponente-checkbox-v2-pomenyat-label-s-string-na-string-ReactNode
> task(AP-852): [FRONT] - change checkbox label

- packages/ui-react/src/components/input-date/index.module.pcss
- fix styles for date-input (task AP-1083)
-
> task(fix-datepicker-input-size):

- packages/ui-react/src/components/modal/v1/index.tsx
- packages/ui-react/src/components/modal/v2/index.tsx
> task(AP-1331): [FRONT] - в ките отключить закрывание модального окна на событие mouseup

- packages/ui-react/src/components/date-picker/index.tsx
Добавил пропсу `dateFormat`, чтобы можно было управлять форматированием.
> task(AP-1328): Подготовить ЛК wb продвижения к мультиязычности

- packages/ui-react/src/components/icons/flags/cn.tsx
- packages/ui-react/src/components/icons/flags/gb.tsx
- packages/ui-react/src/index.ts
Добавил иконки флагов для CN и GB
> task(AP-1280): Поддержка мультиязычности

- packages/ui-react/src/components/counter/index.module.pcss
- packages/ui-react/src/components/counter/index.tsx
- packages/ui-react/src/components/counter/stories/index.stories.tsx
Добавлен новый цвет для счетчика
> AP-938: add purple preset for counter

- .eslintrc.yaml
- package-lock.json
- package.json
Добавил правило для отслеживания пропущенных зависимостей
> chore: add react-hook rule for eslint

- packages/ui-react/src/components/select/index.tsx
> task(AP-1570): [FRONT] Доработать Select для пагинации

- packages/ui-react/src/components/date-picker/index.tsx
> task(AP-1252): [FRONT] Почистить проект от console

- packages/ui-react/src/components/icons/note-text.tsx
- packages/ui-react/src/index.ts
> task(AP-3149): add note text icon
